name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.17, 1.18]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            GOOS=windows GOARCH=amd64 go build -o httgo.exe .
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            GOOS=linux GOARCH=amd64 go build -o httgo-linux .
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            GOOS=darwin GOARCH=amd64 go build -o httgo-macos .
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: httgo-${{ matrix.os }}
          path: |
            httgo.exe
            httgo-linux
            httgo-macos

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: |
            httgo-ubuntu-latest
            httgo-windows-latest
            httgo-macos-latest

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            httgo.exe
            httgo-linux
            httgo-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
